package net.nicomar2009.lsmmod.block;

/** Generated by tools/create_classroom_wall_assets.py; boxes match the models. */
public final class SchoolDecorationShapes {
    private SchoolDecorationShapes() {}
    public static final double[][] PROJECTOR = {
        {2, 2, 15, 14, 14, 16},
        {6, 8, 7, 10, 10, 15},
        {5, 7, 9, 11, 8, 14},
        {2, 4, 2, 14, 5, 9},
        {1, 5, 1, 15, 9, 10},
        {3, 9, 2, 13, 10, 9},
        {3, 6, 0.5, 13, 7.25, 1},
        {4, 9.95, 3, 7, 10.15, 5},
    };
    public static final double[][] TIMETABLE = {
        {1, 4.5, 15, 15, 11.5, 16},
    };
    public static final double[][] BACKPACK = {
        {4, 2, 11, 12, 12, 15},
        {5, 12, 12, 11, 14, 15},
        {5, 1, 12, 11, 2, 15},
        {4.5, 3, 9.5, 11.5, 7, 11},
        {4.5, 7, 9.5, 11.5, 7.4, 11},
        {4, 3, 15, 5, 12, 16},
        {11, 3, 15, 12, 12, 16},
        {6, 14, 13, 7, 15, 14},
        {9, 14, 13, 10, 15, 14},
        {6, 15, 13, 10, 15.5, 14},
    };
}
