"""Correct the toilet cubicle and add an adult urinal, preserving the child fixture."""
from copy import deepcopy
import json

from create_bathroom_statue_assets import ROOT, ASSETS, DATA, TOILET, URINAL, solid_model, write_json

TOILET_CLOSED = deepcopy(TOILET)
for part in TOILET_CLOSED[:2]: part[0][4] = 32
TOILET_OPEN = deepcopy(TOILET_CLOSED)
TOILET_CLOSED += [([1, 0, 0, 15, 32, 1], "partition"),
                  ([12, 13.5, 1, 13, 14.5, 1.375], "chrome"),
                  ([12, 13.5, 0, 13, 14.5, .125], "chrome")]
TOILET_OPEN += [([1, 0, 1, 2, 32, 15], "partition"),
                ([2, 13.5, 12, 2.375, 14.5, 13], "chrome")]
ADULT = deepcopy(URINAL)
for part in ADULT:
    part[0][1] *= 32/15.5
    part[0][4] *= 32/15.5


def split_model(parts, half):
    value = solid_model(parts)
    low, high = (0, 16) if half == "lower" else (16, 32)
    elements = []
    for e in value["elements"]:
        if e["to"][1] <= low or e["from"][1] >= high: continue
        if e["from"][1] < low: e["faces"].pop("down", None)
        if e["to"][1] > high: e["faces"].pop("up", None)
        e["from"][1] = max(low, e["from"][1])-low
        e["to"][1] = min(high, e["to"][1])-low
        if e["faces"]: elements.append(e)
    value["elements"] = elements
    return value


def main():
    geometry = {"TOILET_CLOSED": TOILET_CLOSED, "TOILET_OPEN": TOILET_OPEN, "ADULT_URINAL": ADULT}
    java = ["package net.nicomar2009.lsmmod.block;", "", "/** Generated by tools/create_tall_bathroom_assets.py. */",
            "public final class TallBathroomShapes {", "    private TallBathroomShapes() {}"]
    for name, parts in geometry.items():
        java.append(f"    public static final double[][] {name} = {{")
        java += ["        {"+", ".join(str(v) for v in p[0])+"}," for p in parts]
        java.append("    };")
    java.append("}")
    (ROOT / "src/main/java/net/nicomar2009/lsmmod/block/TallBathroomShapes.java").write_text("\n".join(java)+"\n")
    for block_id, closed, opened in (("toilet", TOILET_CLOSED, TOILET_OPEN), ("adult_men_urinal", ADULT, ADULT)):
        variants = {}
        for half in ("lower", "upper"):
            for is_open, parts in ((False, closed), (True, opened)):
                name = f"{block_id}_{half}_{'open' if is_open else 'closed'}"
                write_json(ASSETS / f"models/block/{name}.json", split_model(parts, half))
                for facing, angle in (("north", 0), ("east", 90), ("south", 180), ("west", 270)):
                    key = f"facing={facing},half={half},open={str(is_open).lower()}"
                    variants[key] = {"model": f"lsmmod:block/{name}", "y": angle}
        write_json(ASSETS / f"blockstates/{block_id}.json", {"variants": variants})
        # Keep the former model path as an alias, rather than leaving an obsolete cubicle there.
        write_json(ASSETS / f"models/block/{block_id}.json", {"parent": f"lsmmod:block/{block_id}_lower_closed"})
        item = solid_model(closed)
        for e in item["elements"]:
            e["from"] = [4+e["from"][0]/2, e["from"][1]/2, 4+e["from"][2]/2]
            e["to"] = [4+e["to"][0]/2, e["to"][1]/2, 4+e["to"][2]/2]
        write_json(ASSETS / f"models/item/{block_id}.json", item)
        write_json(ASSETS / f"items/{block_id}.json", {"model": {"type": "minecraft:model", "model": f"lsmmod:item/{block_id}"}})
        write_json(DATA / f"lsmmod/loot_table/blocks/{block_id}.json", {"type": "minecraft:block", "pools": [{"rolls": 1,
            "conditions": [{"condition": "minecraft:survives_explosion"}, {"condition": "minecraft:block_state_property", "block": f"lsmmod:{block_id}", "properties": {"half": "lower"}}],
            "entries": [{"type": "minecraft:item", "name": f"lsmmod:{block_id}"}]}]})
    for locale, names in (("es_es", {"toilet": "Inodoro con cubículo", "men_urinal": "Urinario infantil", "adult_men_urinal": "Urinario de varones para adultos"}),
                          ("en_us", {"toilet": "Toilet Cubicle", "men_urinal": "Children's Urinal", "adult_men_urinal": "Adult Men's Urinal"})):
        p = ASSETS / f"lang/{locale}.json"; values = json.loads(p.read_text())
        for key, value in names.items(): values[f"block.lsmmod.{key}"] = value
        write_json(p, values)
    p = DATA / "minecraft/tags/block/mineable/pickaxe.json"; value = json.loads(p.read_text())
    if "lsmmod:adult_men_urinal" not in value["values"]: value["values"].append("lsmmod:adult_men_urinal")
    write_json(p, value)


if __name__ == "__main__": main()
