"""Generate two passive plastic swing-lid bins and matching collision geometry."""
import json
import random
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/main/resources/assets/lsmmod"
DATA = ROOT / "src/main/resources/data"
BODY = [
    ([4.5, 0, 5, 11.5, 1, 11], "base"),
    ([4.25, 1, 4.75, 11.75, 4, 11.25], "body"),
    ([4, 4, 4.5, 12, 7.5, 11.5], "body"),
    ([3.5, 7.5, 4, 12.5, 10.5, 12], "body"),
]
GREEN = BODY + [
    ([2.75, 10.5, 3.25, 13.25, 11.5, 12.75], "rim"),
    ([3, 11.5, 3.5, 13, 12.5, 12.5], "lid"),
    ([4, 12.5, 4.5, 12, 14, 11.5], "lid"),
    ([5.5, 14, 5.5, 10.5, 15.5, 10.5], "lid"),
    ([4.75, 12.55, 4.35, 11.25, 13.15, 4.5], "seam"),
    ([5, 13.15, 4.35, 11, 13.6, 4.5], "flap"),
    ([5.5, 14.02, 5.35, 10.5, 14.35, 5.5], "seam"),
]
BLACK = BODY + [
    ([3, 10.5, 3.25, 13, 11.5, 12.75], "rim"),
    ([2.75, 11.5, 4.5, 13.25, 12.25, 11.5], "lid"),
    ([3.5, 11.5, 3.5, 12.5, 12.25, 12.5], "lid"),
    ([3.75, 12.25, 4.25, 12.25, 13, 11.75], "lid"),
    ([5, 13, 5, 11, 13.5, 11], "flap"),
    ([4.25, 12.3, 4.1, 11.75, 12.8, 4.25], "seam"),
    ([2.5, 10.75, 6, 3, 11.35, 10], "rim"),
    ([13, 10.75, 6, 13.5, 11.35, 10], "rim"),
]
VARIANTS = {
    "green_trash_bin": (GREEN, (30, 143, 68), "Tacho de basura verde", "Green Trash Bin"),
    "black_trash_bin": (BLACK, (37, 39, 38), "Tacho de basura negro", "Black Trash Bin"),
}


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2)+"\n", encoding="utf-8")


def texture(block_id, material, base):
    offsets = {"body": 0, "base": -9, "rim": -6, "lid": 7, "flap": 2, "seam": -23}
    image = Image.new("RGB", (16, 16))
    rng = random.Random(842)
    for y in range(16):
        for x in range(16):
            shade = offsets[material]+rng.choice((-1, 0, 0, 0, 1))
            if material == "body":
                if x in (1, 14): shade -= 3
                if x in (3, 4): shade += 2
            color = tuple(max(0, min(255, v+shade)) for v in base)
            image.putpixel((x, y), color)
    path = ASSETS / f"textures/block/{block_id}_{material}.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def main():
    java = ["package net.nicomar2009.lsmmod.block;", "", "/** Generated by tools/create_school_bin_assets.py. */",
            "public final class TrashBinShapes {", "    private TrashBinShapes() {}"]
    for block_id, (parts, base, _, _) in VARIANTS.items():
        elements = []
        for bounds, material in parts:
            elements.append({"from": bounds[:3], "to": bounds[3:],
                             "faces": {f: {"texture": "#"+material, "uv": [0, 0, 16, 16]}
                                       for f in ("north", "south", "east", "west", "up", "down")}})
        materials = sorted({material for _, material in parts})
        for material in materials: texture(block_id, material, base)
        textures = {m: f"lsmmod:block/{block_id}_{m}" for m in materials}
        textures["particle"] = textures["body"]
        write_json(ASSETS / f"models/block/{block_id}.json", {
            "parent": "minecraft:block/block", "textures": textures, "elements": elements})
        write_json(ASSETS / f"blockstates/{block_id}.json", {"variants": {
            f"facing={f}": {"model": f"lsmmod:block/{block_id}", "y": angle}
            for f, angle in (("north", 0), ("east", 90), ("south", 180), ("west", 270))}})
        write_json(ASSETS / f"models/item/{block_id}.json", {"parent": f"lsmmod:block/{block_id}"})
        write_json(ASSETS / f"items/{block_id}.json", {"model": {"type": "minecraft:model", "model": f"lsmmod:item/{block_id}"}})
        write_json(DATA / f"lsmmod/loot_table/blocks/{block_id}.json", {
            "type": "minecraft:block", "pools": [{"rolls": 1,
                "conditions": [{"condition": "minecraft:survives_explosion"}],
                "entries": [{"type": "minecraft:item", "name": f"lsmmod:{block_id}"}]}]})
        name = "GREEN" if block_id.startswith("green") else "BLACK"
        java.append(f"    public static final double[][] {name} = {{")
        java += ["        {"+", ".join(str(v) for v in bounds)+"}," for bounds, _ in parts]
        java.append("    };")
    java.append("}")
    (ROOT / "src/main/java/net/nicomar2009/lsmmod/block/TrashBinShapes.java").write_text("\n".join(java)+"\n")
    for locale, index in (("es_es", 2), ("en_us", 3)):
        path = ASSETS / f"lang/{locale}.json"
        values = json.loads(path.read_text())
        for block_id, variant in VARIANTS.items(): values[f"block.lsmmod.{block_id}"] = variant[index]
        write_json(path, values)


if __name__ == "__main__":
    main()
